"use client";
/* eslint-disable @next/next/no-img-element */
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
import {parseReport,type InbodyReport} from '@/lib/inbody-report';
import {CustomerLogin} from '@/components/CustomerAccess';
const InbodyImport=dynamic(()=>import('@/components/InbodyImport'),{loading:()=> <p>기록 입력 준비 중…</p>});
const fields=[['weight','체중','kg','#0baa99'],['muscle','골격근량','kg','#507bd1'],['fat','체지방량','kg','#e18d40'],['fatPercent','체지방률','%','#bf659b']] as const;
type Row={id:string;data:InbodyReport;hasImage:boolean;createdAt:string};
const dateLabel=(date:string)=>new Date(date).toLocaleString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
export default function Page(){
 const [rows,setRows]=useState<Row[]>([]),[add,setAdd]=useState(false),[auth,setAuth]=useState<boolean|null>(null),[error,setError]=useState(''),[period,setPeriod]=useState('all'),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[busy,setBusy]=useState(false),[photo,setPhoto]=useState<{image:string;date:string}|null>(null),[loadingPhoto,setLoadingPhoto]=useState<string|null>(null);
 const load=useCallback(async(p=0)=>{setError('');setBusy(true);try{const r=await fetch(`/api/customer/inbody?page=${p}`);if(r.status===401){setAuth(false);setRows([]);return;}if(!r.ok)throw Error('기록을 불러오지 못했습니다.');const d=await r.json();const valid:Row[]=d.records.flatMap((r:Row)=>{const parsed=parseReport(r.data,r.hasImage);return parsed?[{...r,data:parsed}]:[];});setRows(old=>p?[...old,...valid.filter(r=>!old.some(x=>x.id===r.id))]:valid);setHasMore(d.hasMore);setPage(p);setAuth(true);}catch(e){setError(e instanceof Error?e.message:'연결 실패');}finally{setBusy(false);}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- fetch authenticated records
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!photo)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setPhoto(null);};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=prev;window.removeEventListener('keydown',close);};},[photo]);
 const sorted=[...rows].sort((a,b)=>Date.parse(a.data.measuredAt)-Date.parse(b.data.measuredAt));
 const latest=sorted.at(-1);const since=period==='all'?0:Date.parse(latest?.data.measuredAt??'1970-01-01')-Number(period)*86400000;
 const history=sorted.filter(r=>Date.parse(r.data.measuredAt)>=since);
 async function source(row:Row){if(loadingPhoto)return;setError('');if(row.data.image){setPhoto({image:row.data.image,date:row.data.measuredAt});return;}setLoadingPhoto(row.id);try{const r=await fetch(`/api/customer/inbody?id=${encodeURIComponent(row.id)}`);if(!r.ok)throw Error('사진을 불러오지 못했습니다.');const d=await r.json();const data=parseReport(d.record.data);if(!data?.image)throw Error('이 기록에 저장된 사진이 없습니다.');setPhoto({image:data.image,date:data.measuredAt});setRows(old=>old.map(x=>x.id===row.id?{...x,data}:x));}catch(e){setError(e instanceof Error?e.message:'사진 연결 실패');}finally{setLoadingPhoto(null);}}
 return <div className="care-app ib-app"><header className="care-header"><Link href="/">← 홈</Link><b>LULU CARE · 인바디</b><Link href="/customer">내 기록</Link></header><main className="care-main">
 {add?<InbodyImport onCancel={()=>setAdd(false)} onSaved={()=>{setAdd(false);void load();}}/>:<><h1>인바디 변화 기록</h1><p className="muted">네 가지 수치의 변화와 날짜별 결과지 사진을 모아보세요.</p><button className="care-primary" onClick={()=>setAdd(true)}>＋ 결과지 사진 · 수치 추가</button>
 {auth===false&&<CustomerLogin onLogin={()=>void load()}/>}<div className="ib-actions"><button className="text-link" disabled={busy} onClick={()=>void load()}>새로고침</button><label>표시 기간<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">전체 기록</option><option value="30">최근 검사 기준 1개월</option><option value="90">최근 검사 기준 3개월</option><option value="180">최근 검사 기준 6개월</option></select></label></div>{busy&&<p role="status">기록을 불러오는 중…</p>}
 <div className="ib-summary ib-four-summary">{fields.map(([key,label,unit])=>{const records=sorted.filter(r=>r.data.values[key]);const last=records.at(-1),prev=records.at(-2);const value=last?.data.values[key]?.value;const delta=value!==undefined&&prev?value-prev.data.values[key]!.value:null;return <div key={key}><span>{label} ({unit})</span><strong>{value??'—'}</strong><small>{last?new Date(last.data.measuredAt).toLocaleDateString('ko-KR'):'수치 기록 없음'}</small>{delta!==null&&<p className="ib-delta">이전 대비 {delta>0?'+':''}{Number(delta.toFixed(2))} {unit}</p>}</div>;})}</div>
 {fields.map(([key,label,unit,color])=>{const points=history.map(r=>({time:Date.parse(r.data.measuredAt),value:r.data.values[key]?.value??null}));const values=points.flatMap(p=>p.value===null?[]:[p.value]);return <section className="care-card" key={key}><h2>{label} 변화 <small>({unit})</small></h2>{values.length?<><ResponsiveContainer width="100%" height={230}><LineChart data={points} margin={{top:20,right:25,bottom:10,left:0}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={v=>new Date(v).toLocaleDateString('ko-KR',{month:'numeric',day:'numeric'})} tick={{fontSize:11}}/><YAxis domain={['auto','auto']} width={48}/><Tooltip labelFormatter={v=>dateLabel(new Date(Number(v)).toISOString())}/><Line type="linear" dataKey="value" name={`${label} (${unit})`} stroke={color} strokeWidth={3} dot={{r:5}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer><p className="muted small">최저 {Math.min(...values)} · 최고 {Math.max(...values)} · 평균 {Number((values.reduce((a,b)=>a+b,0)/values.length).toFixed(2))} {unit} ({values.length}회)</p></>:<p className="muted">이 기간에 입력된 {label} 수치가 없습니다. 검사 기록에 수치를 입력하면 그래프가 표시됩니다.</p>}</section>;})}
 <section className="care-card"><h2>날짜별 통계 수치</h2><div style={{overflowX:'auto'}}><table className="ib-table"><thead><tr><th>검사일</th>{fields.map(([k,label,unit])=><th key={k}>{label}<br/>({unit})</th>)}</tr></thead><tbody>{[...history].reverse().map(r=><tr key={r.id}><td>{dateLabel(r.data.measuredAt)}</td>{fields.map(([k])=><td key={k}>{r.data.values[k]?.value??'—'}</td>)}</tr>)}</tbody></table></div>{!history.length&&<p>등록된 기록이 없습니다.</p>}<p className="muted small">사진만 저장한 날의 수치는 ‘—’로 표시하며 평균에 포함하지 않습니다.</p></section>
 <section className="care-card"><h2>결과지 사진 보관함</h2><p>사진은 새 기록을 추가해도 이전 사진과 함께 계속 보관됩니다.</p><div className="ib-photo-grid">{[...sorted].reverse().filter(r=>r.hasImage||r.data.image).map(r=><button className="ib-photo-card" key={r.id} disabled={loadingPhoto!==null} onClick={()=>void source(r)}>{r.data.image?<img src={r.data.image} alt={`${dateLabel(r.data.measuredAt)} 결과지`} loading="lazy"/>:<span className="ib-photo-placeholder">결과지 사진</span>}<b>{dateLabel(r.data.measuredAt)}</b><span>{loadingPhoto===r.id?'사진 불러오는 중…':'사진 크게 보기'}</span></button>)}</div>{!sorted.some(r=>r.hasImage||r.data.image)&&<p className="muted">저장된 사진이 없습니다. 결과지를 추가해주세요.</p>}</section>
 {hasMore&&<button className="care-secondary" disabled={busy} onClick={()=>void load(page+1)}>이전 기록 더 보기 · 그래프와 사진에 반영</button>}<p className="muted small">그래프와 통계는 불러온 기록 기준입니다. 기존 기록과 사진은 유지됩니다.</p></>}
 <p role="alert">{error}</p>{photo&&<div className="ib-modal" role="dialog" aria-modal="true" aria-label="결과지 사진"><button autoFocus onClick={()=>setPhoto(null)}>닫기</button><p>{dateLabel(photo.date)}</p><img src={photo.image} alt="저장된 인바디 결과지"/></div>}
 </main></div>;
}
