"use client";
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from 'recharts';
import {METRICS,parseReport,rangeLabel,type InbodyReport,type MetricKey} from '@/lib/inbody-report';
import InbodyReportView from '@/components/InbodyReportView';
import {CustomerLogin} from '@/components/CustomerAccess';
const InbodyImport=dynamic(()=>import('@/components/InbodyImport'),{loading:()=> <p>사진 인식 준비 중…</p>});
type Row={id:string;data:InbodyReport;hasImage:boolean;createdAt:string};
export default function Page(){
 const [now]=useState(()=>Date.now());
 const [rows,setRows]=useState<Row[]>([]),[index,setIndex]=useState(0),[tab,setTab]=useState('대시보드'),[add,setAdd]=useState(false),[auth,setAuth]=useState<boolean|null>(null),[error,setError]=useState(''),[settings,setSettings]=useState(false),[selected,setSelected]=useState<MetricKey[]>(['weight','muscle','fatPercent']),[metric,setMetric]=useState<MetricKey>('weight'),[period,setPeriod]=useState('all'),[page,setPage]=useState(0),[hasMore,setHasMore]=useState(false),[trash,setTrash]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(async(p=0)=>{setError('');setBusy(true);try{const r=await fetch(`/api/customer/inbody?page=${p}`);if(r.status===401){setAuth(false);setRows([]);return;}if(!r.ok)throw Error('기록을 불러오지 못했습니다.');const d=await r.json();const valid:Row[]=d.records.flatMap((r:Row)=>{const parsed=parseReport(r.data);return parsed?[{...r,data:parsed}]:[];});setRows(old=>p?[...old,...valid.filter(r=>!old.some(x=>x.id===r.id))]:valid);setHasMore(d.hasMore);setPage(p);setAuth(true);}catch(e){setError(e instanceof Error?e.message:'연결 실패');}finally{setBusy(false);}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- hydrate browser preferences and fetch authenticated records
 useEffect(()=>{void load();try{const x=JSON.parse(localStorage.getItem('lulu-inbody-fields')||'null');if(Array.isArray(x)&&x.length===3&&new Set(x).size===3&&x.every(k=>METRICS.some(m=>m[0]===k)))setSelected(x);}catch{}},[load]);
 const sorted=rows.filter(r=>!!r.data.archived===trash).sort((a,b)=>Date.parse(b.data.measuredAt)-Date.parse(a.data.measuredAt));const current=sorted[Math.min(index,Math.max(0,sorted.length-1))];const previous=sorted[Math.min(index,Math.max(0,sorted.length-1))+1]?.data;
 const meta=METRICS.find(m=>m[0]===metric)!;const since=period==='all'?0:now-Number(period)*86400000;const history=[...sorted].reverse().filter(r=>Date.parse(r.data.measuredAt)>=since).map(r=>({date:new Date(r.data.measuredAt).toLocaleDateString('ko-KR'),value:r.data.values[metric]?.value??null}));
 async function archive(){if(!current||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/customer/inbody',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:current.id,archived:!trash})});if(!r.ok)throw Error('기록 변경에 실패했습니다.');setIndex(0);await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function source(){if(!current)return;setError('');try{const r=await fetch(`/api/customer/inbody?id=${encodeURIComponent(current.id)}`);if(!r.ok)throw Error('사진을 불러오지 못했습니다.');const d=await r.json();setRows(old=>old.map(x=>x.id===current.id?{...x,data:d.record.data}:x));}catch(e){setError(String(e));}}
 async function share(){if(!current)return;const text=`LULU CARE 인바디 기록 · ${new Date(current.data.measuredAt).toLocaleString('ko-KR')}\n`+METRICS.filter(m=>current.data.values[m[0]]).map(([k,label,unit])=>`${label}: ${current.data.values[k]!.value} ${unit}`).join('\n');try{if(navigator.share)await navigator.share({title:'내 인바디 검사 기록',text});else{const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='inbody-report.txt';a.click();URL.revokeObjectURL(url);}}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError('공유하지 못했습니다. 다시 시도해 주세요.');}}
 return <div className="care-app ib-app"><header className="care-header"><Link href="/">← 홈</Link><b>LULU CARE · 인바디</b><Link href="/customer">내 기록</Link></header><main className="care-main">
 {add?<InbodyImport onCancel={()=>setAdd(false)} onSaved={()=>{setAdd(false);setIndex(0);setTrash(false);void load();}}/>:<><h1>내 몸의 변화를 한눈에</h1><p className="muted">인바디 결과지 사진으로 기록하는 체성분 리포트</p><button className="care-primary" onClick={()=>setAdd(true)}>＋ 결과지 촬영 · 검사기록 추가</button><nav className="ib-tabs" aria-label="인바디 리포트">{['대시보드','상세','변화','개인 순위'].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {auth===false&&<CustomerLogin onLogin={()=>void load()}/>}<div className="ib-actions"><button className="text-link" disabled={busy} onClick={()=>{setIndex(0);void load();}}>새로고침</button><button className="text-link" onClick={()=>{setTrash(t=>!t);setIndex(0);}}>{trash?'현재 기록 보기':'보관함'}</button></div>{busy&&<p role="status">기록을 불러오는 중…</p>}
 {!current?<section className="care-card empty-panel"><h2>{trash?'보관된 기록이 없습니다':'첫 인바디 기록을 추가해 주세요'}</h2><p>사진 인식 후 수치를 확인하면 요약·상세·변화가 표시됩니다.</p></section>:<><div className="ib-record-date"><button disabled={index>=sorted.length-1} onClick={()=>setIndex(i=>i+1)} aria-label="이전 검사">‹</button><span>{new Date(current.data.measuredAt).toLocaleString('ko-KR')}</span><button disabled={index===0} onClick={()=>setIndex(i=>i-1)} aria-label="다음 검사">›</button></div>
 {tab==='대시보드'&&<><div className="ib-heading"><h2>인바디검사 요약</h2><button className="text-link" onClick={()=>setSettings(true)}>표시항목 설정</button></div><div className="ib-summary">{selected.map(k=>{const m=METRICS.find(x=>x[0]===k)!;const r=current.data.values[k];return <button key={k} aria-pressed={metric===k} onClick={()=>setMetric(k)}><span>{m[1]} ({m[2]})</span><strong>{r?.value??'—'}</strong><small className={`ib-badge ${rangeLabel(r)==='표준'?'normal':''}`}>{rangeLabel(r)}</small></button>;})}</div></>}
 {(tab==='대시보드'||tab==='변화')&&<section className="care-card"><h2>{meta[1]} 변화</h2><div className="ib-actions"><label>항목<select value={metric} onChange={e=>setMetric(e.target.value as MetricKey)}>{METRICS.map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></label><label>기간<select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">전체</option><option value="30">1개월</option><option value="90">3개월</option><option value="180">6개월</option></select></label></div><ResponsiveContainer width="100%" height={260}><LineChart data={history} margin={{top:20,right:15,bottom:10,left:0}}><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis domain={['auto','auto']} width={42}/><Tooltip/><Line type="linear" dataKey="value" name={`${meta[1]} (${meta[2]})`} stroke="#0baa99" strokeWidth={3} dot={{r:5}} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer><p className="muted small">누락된 값은 0으로 채우지 않습니다. 비교는 실제 검사일 순서입니다.</p>{tab==='변화'&&<table className="ib-table"><thead><tr><th>검사일</th><th>{meta[1]}</th></tr></thead><tbody>{history.map((r,i)=><tr key={i}><td>{r.date}</td><td>{r.value??'미기재'} {meta[2]}</td></tr>)}</tbody></table>}</section>}
 {tab==='상세'&&<InbodyReportView report={current.data} previous={previous} onImage={()=>void source()} hasImage={current.hasImage}/>}
 {tab==='개인 순위'&&<section className="care-card"><h2>내 인바디점수 기록 순위</h2><p className="muted">내가 저장한 점수끼리만 비교합니다. 다른 회원이나 인바디 전체 이용자의 순위가 아닙니다.</p><ol className="ib-ranking">{sorted.filter(r=>r.data.values.score).sort((a,b)=>b.data.values.score!.value-a.data.values.score!.value).map(r=><li key={r.id}><span>{new Date(r.data.measuredAt).toLocaleDateString('ko-KR')}</span><strong>{r.data.values.score!.value}점</strong></li>)}</ol>{!sorted.some(r=>r.data.values.score)&&<p>결과지에 기재된 인바디점수를 입력해 주세요.</p>}</section>}
 <div className="ib-actions"><button className="care-secondary" onClick={()=>void share()}>공유하기</button><button className="care-secondary" onClick={()=>window.print()}>인쇄 · PDF</button><button className="text-link" disabled={busy} onClick={()=>void archive()}>{trash?'기록 복원':'기록 보관함으로 이동'}</button></div></>}
 {hasMore&&<button className="care-secondary" disabled={busy} onClick={()=>void load(page+1)}>이전 기록 더 불러오기 · 그래프에도 반영</button>}<p className="muted small">인바디 기기·공식 앱과 자동 동기화되지 않습니다. 직접 등록한 결과지의 정보를 표시합니다.</p></>}
 <p role="alert">{error}</p>
 {settings&&<div className="ib-modal" role="dialog" aria-modal="true" aria-label="표시항목 설정"><section className="care-card"><h2>요약에 표시할 3가지 항목</h2><p>체크한 순서대로 표시됩니다. 화살표로 순서를 바꾸세요.</p>{selected.map((k,i)=><div className="ib-order" key={k}><span>{i+1}. {METRICS.find(m=>m[0]===k)![1]}</span><button disabled={i===0} aria-label={`${k} 위로`} onClick={()=>setSelected(s=>{const n=[...s];[n[i-1],n[i]]=[n[i],n[i-1]];return n;})}>↑</button><button disabled={i===selected.length-1} aria-label={`${k} 아래로`} onClick={()=>setSelected(s=>{const n=[...s];[n[i+1],n[i]]=[n[i],n[i+1]];return n;})}>↓</button></div>)}{METRICS.map(([k,label])=><label className="check-label" key={k}><input type="checkbox" checked={selected.includes(k)} disabled={!selected.includes(k)&&selected.length>=3} onChange={e=>setSelected(s=>e.target.checked?[...s,k]:s.filter(v=>v!==k))}/>{label}</label>)}<button className="care-primary" disabled={selected.length!==3} onClick={()=>{try{localStorage.setItem('lulu-inbody-fields',JSON.stringify(selected));}catch{}setSettings(false);}}>적용</button></section></div>}
 </main></div>;
}
