"use client";
/* eslint-disable @next/next/no-img-element */
import {useState} from 'react';
import {METRICS,SEGMENTS,SEGMENT_LABELS,rangeLabel,type InbodyReport,type Reading} from '@/lib/inbody-report';
function Delta({a,b}:{a?:number;b?:number}){return <small className="ib-delta">{a===undefined||b===undefined?'비교 기록 없음':`${a-b>0?'+':''}${Number((a-b).toFixed(3))}`}</small>;}
function RangeBar({r}:{r:Reading}){if(r.low===undefined||r.high===undefined)return <small className="muted">결과지 표준 범위를 입력하면 비교됩니다.</small>;const max=Math.max(r.high*1.5,r.value,1);return <div className="ib-range"><div><i style={{left:`${r.low/max*100}%`,width:`${(r.high-r.low)/max*100}%`}}/><b style={{left:`${Math.min(99,r.value/max*100)}%`}}/></div><small>결과지 표준 {r.low}–{r.high} · {rangeLabel(r)}</small></div>;}
export default function InbodyReportView({report,previous,onImage,hasImage=false,sourceLink}:{report:InbodyReport;previous?:InbodyReport;onImage?:()=>void;hasImage?:boolean;sourceLink?:string}){
 const [mode,setMode]=useState<'muscle'|'fat'>('muscle'),[large,setLarge]=useState(false);
 const segment=report.segments[mode];const percents=SEGMENTS.map(k=>segment[k]?.percent);const all=percents.every(v=>v!==undefined);const max=Math.max(150,...percents.map(v=>v??0));
 const point=(i:number,v:number)=>{const angle=-Math.PI/2+i*2*Math.PI/5;return `${150+Math.cos(angle)*100*v/max},${135+Math.sin(angle)*100*v/max}`;};
 return <div className="ib-report"><section className="care-card"><h2>종합 요약</h2><div className="ib-summary">{(['bodyAge','score'] as const).map(k=><div key={k}><span>{k==='score'?'인바디점수':'인바디나이'}</span><strong>{report.values[k]?.value??'—'}<small>{k==='score'?'점':'세'}</small></strong><Delta a={report.values[k]?.value} b={previous?.values[k]?.value}/></div>)}</div><p className="muted small">검사지에 기재된 값만 표시합니다. 미기재 점수·나이는 추정하지 않습니다.</p></section>
 <section className="care-card"><h2>부위별 분석</h2><div className="ib-tabs"><button aria-pressed={mode==='muscle'} onClick={()=>setMode('muscle')}>근육량</button><button aria-pressed={mode==='fat'} onClick={()=>setMode('fat')}>체지방</button></div><svg viewBox="0 0 300 280" className="ib-radar" role="img" aria-label={`부위별 ${mode==='muscle'?'근육량':'체지방'} 표준 대비 비율`}>{[.25,.5,.75,1].map(v=><polygon key={v} points={SEGMENTS.map((_,i)=>point(i,max*v)).join(' ')} fill="none" stroke="#dbe4e6"/>)}{all&&<polygon points={percents.map((v,i)=>point(i,v!)).join(' ')} fill="#0baa9966" stroke="#0baa99" strokeWidth="2"/>}{SEGMENTS.map((k,i)=>{const [x,y]=point(i,max*1.15).split(',');return <text key={k} x={x} y={y} textAnchor="middle" fontSize="11" fill="#52626c">{SEGMENT_LABELS[k]} {segment[k]?.percent??'—'}%</text>;})}{!all&&<text x="150" y="140" textAnchor="middle" fontSize="12">부위별 % 입력 후 그래프 표시</text>}</svg><div className="ib-segment-list">{SEGMENTS.map(k=><div key={k}><span>{SEGMENT_LABELS[k]}</span><b>{segment[k]?.kg??'—'} kg</b><span>{segment[k]?.percent??'—'}%</span><Delta a={segment[k]?.kg} b={previous?.segments[mode][k]?.kg}/></div>)}</div><p className="muted small">%는 결과지의 표준 대비 비율입니다. 부위별 체지방 %는 전체 체지방률과 다릅니다.</p></section>
 {[...new Set(METRICS.map(m=>m[4]))].map(group=><section key={group} className="care-card"><h2>{group}</h2>{METRICS.filter(m=>m[4]===group).map(([key,label,unit])=>{const r=report.values[key];return <div className="ib-metric" key={key}><div><span>{label}</span><strong>{r?.value??'—'} <small>{unit}</small></strong><Delta a={r?.value} b={previous?.values[key]?.value}/></div>{r?<RangeBar r={r}/>:<small className="muted">결과지 미기재</small>}</div>;})}</section>)}
 <section className="care-card"><h2>체형 좌표 · CID 유형</h2><p>{report.bodyType||'결과지 체형 분류 미기재'} · {report.cid||'CID 유형 미기재'}</p><svg viewBox="0 0 320 250" className="ib-coordinate" role="img" aria-label="BMI와 체지방률 좌표"><rect x="40" y="15" width="250" height="190" rx="16" fill="#edf2f4"/>{[0,20,40,60].map(n=><g key={n}><line x1={40+n/60*250} y1="15" x2={40+n/60*250} y2="205" stroke="white"/><text x={40+n/60*250} y="223" fontSize="10" textAnchor="middle">{n}</text></g>)}{[10,20,30,40,50].map(n=><g key={n}><line x1="40" y1={205-(n-10)/40*190} x2="290" y2={205-(n-10)/40*190} stroke="white"/><text x="26" y={209-(n-10)/40*190} fontSize="10">{n}</text></g>)}{report.values.bmi&&report.values.fatPercent&&report.values.bmi.value>=10&&report.values.bmi.value<=50&&report.values.fatPercent.value<=60&&<circle cx={40+report.values.fatPercent.value/60*250} cy={205-(report.values.bmi.value-10)/40*190} r="7" fill="#ef6280"/>}<text x="40" y="10" fontSize="11">BMI</text><text x="240" y="242" fontSize="11">체지방률 %</text></svg><p className="muted small">좌표 범위: BMI 10–50, 체지방률 0–60%. 범위 밖의 값은 위 수치에서 확인하세요. 체형 분류와 CID는 결과지 문구를 그대로 기록하며 새로 진단하지 않습니다.</p></section>
 <section className="care-card"><h2>검사 결과지 사진</h2>{report.image?<button className="ib-source" onClick={()=>setLarge(true)}><img src={report.image} alt="저장한 인바디 검사 결과지"/><span>사진 확대 보기</span></button>:hasImage&&onImage?<button className="care-secondary" onClick={onImage}>결과지 사진 불러오기</button>:hasImage&&sourceLink?<a className="care-secondary" href={sourceLink}>인바디 화면에서 결과지 사진 보기</a>:<p className="muted">저장된 결과지 사진이 없습니다.</p>}</section>
 {large&&report.image&&<div className="ib-modal" role="dialog" aria-modal="true" aria-label="인바디 결과지 확대"><button onClick={()=>setLarge(false)}>닫기 ×</button><img src={report.image} alt="인바디 결과지 확대"/></div>}
 </div>;
}
